pipeline:
  build:
    image: google/dart:${DART_VERSION}
    pull: true
    commands:
      - sh build.sh
    environment:
      - DARTANALYZER_FLAGS=--fatal-warnings

  coverage:
    image: plugins/coverage
    server: https://aircover.co
    when:
      matrix:
        DART_VERSION: dev

matrix:
  DART_VERSION:
    - latest
    - dev
